spring:
  application:
    name: gateway-server
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    gateway:
      discovery:
        # this enable eureka path
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/service/**
          filters:
            - RewritePath=/service/(?<path>.*), /$\{path}
      # use service discovery as route
    loadbalancer.ribbon.enabled: false

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
